spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.26.160.246:3306/demo?useUnicode=true&useSSL=true
    username: root
    password: 123456
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
